version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "DEVELOPER"
    ports:
      - "1433:1433"
    networks:
      - app_network

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

